IzintoCleaning/Models/CleaningOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations.Schema;


namespace IzintoCleaning.Models
{
    public class CleaningOrder
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Order_ID { get; set; }

        public int Package_ID { get; set; }
        [ForeignKey("Package_ID")]
        public virtual Cleaning Cleaning { get; set; }

        public string CustID { get; set; }
        [ForeignKey("CustID")]
        public virtual Customer Customer { get; set; }

        [Required(ErrorMessage = "Enter the area of the house to be cleaned")]
        [Range(30, 200, ErrorMessage = "Size of house must be between 30 and 200 square meters")]
        public decimal area { get; set; }

        [Required(ErrorMessage = "Enter the number of floors to be cleaned")]
        [Range(1, 4, ErrorMessage = "We clean builidings with 1-4 floors")]
        public int storey { get; set; }
        public bool Confirm { get; set; }

        [DataType(DataType.Currency)]
        public decimal cost { get; set; }

        [Column("ServiceDate", TypeName = "datetime2")]
        [DisplayName("Date Of Service")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Please select the date you want the service perfomed")]
        public DateTime DateOfService { get; set; }

        [DisplayName("Cost Per 30 sq meter")]
        [DataType(DataType.Currency)]
        public decimal areacost { get; set; }
         public bool paymentstatus { get; set; }

        [DisplayName("Cost Per Floor")]
        [DataType(DataType.Currency)]
        public decimal floorcost { get; set; }

        //[ForeignKey("EmpId")]
        //public virtual Employee employee { get; set; }
        //public int? EmpId { get; set; }
        public string EmpmloyeeName { get; set; }

        public string address { get; set; }

        ApplicationDbContext db = new ApplicationDbContext();

        //public void Assign()
        //{

        //    var asign = (from i in db.Employees where EmpId == i.EmpID select i.Status).SingleOrDefault();
        //    asign = "Not Available";
        //    db.SaveChanges();
        //}

        //public string getAssign()
        //{
        //    var asign = (from i in db.Employees where EmpId == i.EmpID select i.Status).SingleOrDefault();
        //    return asign;
        //}

        public decimal getCostArea()
        {
            var cost = (from i in db.Cleanings where Package_ID == i.Package_ID select i.CostArea).SingleOrDefault();
            return cost;
        }

        public decimal getFloorCost()
        {
            var cost = (from i in db.Cleanings where Package_ID == i.Package_ID select i.CostStorey).SingleOrDefault();
            return cost;
        }

        public decimal calcFinal()
        {
            decimal final;
            decimal a = (area / 30) * getCostArea();
            decimal s = storey * getFloorCost();
            final = a + s;
            return final;

        }
    }
}

IzintoCleaning/Controllers/CleaningOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IzintoCleaning.Models;
using Microsoft.AspNet.Identity;
using PayFast;
using PayFast.AspNet;
using System.Configuration;
using System.Threading.Tasks;


namespace IzintoCleaning.Controllers
{
    public class CleaningOrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CleaningOrders
        public CleaningOrdersController()
        {
            this.payFastSettings = new PayFastSettings();
            this.payFastSettings.MerchantId = ConfigurationManager.AppSettings["MerchantId"];
            this.payFastSettings.MerchantKey = ConfigurationManager.AppSettings["MerchantKey"];
            this.payFastSettings.PassPhrase = ConfigurationManager.AppSettings["PassPhrase"];
            this.payFastSettings.ProcessUrl = ConfigurationManager.AppSettings["ProcessUrl"];
            this.payFastSettings.ValidateUrl = ConfigurationManager.AppSettings["ValidateUrl"];
            this.payFastSettings.ReturnUrl = ConfigurationManager.AppSettings["ReturnUrl"];
            this.payFastSettings.CancelUrl = ConfigurationManager.AppSettings["CancelUrl"];
            this.payFastSettings.NotifyUrl = ConfigurationManager.AppSettings["NotifyUrl"];
        }

        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                var id = User.Identity.GetUserId();
                var cleaningOrder1 = db.CleaningOrders.Include(c => c.Cleaning).Include(c => c.Customer);
                return View(cleaningOrder1.ToList());//.Where(x => x.CustID == id));
            }
            var userid = User.Identity.GetUserId();
            var cleaningorder = db.CleaningOrders.Include(c => c.Cleaning).Include(c => c.Customer).Where(x => x.CustID == userid).Where(x=>x.paymentstatus==false);

            //var cleaningOrders = db.CleaningOrders.Include(c => c.Cleaning).Include(c => c.Customer);
            return View(cleaningorder.ToList());
        }

        public ActionResult PrevOrders()
        {
            var userid = User.Identity.GetUserId();
            var cleaningorder = db.CleaningOrders.Include(c => c.Cleaning).Include(c => c.Customer).Where(x => x.CustID == userid).Where(x => x.paymentstatus == true);
            return View(cleaningorder.ToList());
        }
        //public ActionResult Confirmation()
        //{
        //    var cleaningOrders = db.CleaningOrders.Include(c => c.Cleaning).Include(c => c.Customer).Where(c=>c.!=null);
        //    return View(cleaningOrders.ToList());
        //}

        // GET: CleaningOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CleaningOrder cleaningOrder = db.CleaningOrders.Find(id);
            if (cleaningOrder == null)
            {
                return HttpNotFound();
            }
            return View(cleaningOrder);
        }

        // GET: CleaningOrders/Create
        public ActionResult Create()
        {
            ViewBag.Package_ID = new SelectList(db.Cleanings, "Package_ID", "PackageName");
            var userid = User.Identity.GetUserId();
            ViewBag.CustID = new SelectList(db.customer.Where(c => c.CustID == userid), "CustID", "CustName");
       
            return View();
        }

        // POST: CleaningOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Order_ID,Package_ID,CustID,area,storey,cost,DateOfService,address")] CleaningOrder cleaningOrder)
        {
            if (ModelState.IsValid)
            {
                string str = Request.Params["btn1"];
                if (str == "View Final Amount")
                {
                    cleaningOrder.cost = cleaningOrder.calcFinal();
                    cleaningOrder.areacost = cleaningOrder.getCostArea();
                    cleaningOrder.floorcost = cleaningOrder.getFloorCost();
                   // cleaningOrder.showStatus = cleaningOrder.getAssign();
                }
                else if (str == "Confirm Order")
                {
                    cleaningOrder.cost = cleaningOrder.calcFinal();
                    cleaningOrder.areacost = cleaningOrder.getCostArea();
                    cleaningOrder.floorcost = cleaningOrder.getFloorCost();

                    db.CleaningOrders.Add(cleaningOrder);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Package_ID = new SelectList(db.Cleanings, "Package_ID", "PackageName", cleaningOrder.Package_ID);
            ViewBag.CustID = new SelectList(db.customer, "CustID", "CustName", cleaningOrder.CustID);
   
            return View(cleaningOrder);
        }

        // GET: CleaningOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CleaningOrder cleaningOrder = db.CleaningOrders.Find(id);
            if (cleaningOrder == null)
            {
                return HttpNotFound();
            }
            var userid = User.Identity.GetUserId();
            ViewBag.Package_ID = new SelectList(db.Cleanings, "Package_ID", "PackageName", cleaningOrder.Package_ID);
            ViewBag.CustID = new SelectList(db.customer.Where(c => c.CustID == userid), "CustID", "CustName", cleaningOrder.CustID);
          
            return View(cleaningOrder);
        }

        // POST: CleaningOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Order_ID,Package_ID,CustID,area,storey,cost,DateOfService,EmpId,address")] CleaningOrder cleaningOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cleaningOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Package_ID = new SelectList(db.Cleanings, "Package_ID", "PackageName", cleaningOrder.Package_ID);
            ViewBag.CustID = new SelectList(db.customer, "CustID", "CustName", cleaningOrder.CustID);
         
            return View(cleaningOrder);
        }

        // GET: CleaningOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CleaningOrder cleaningOrder = db.CleaningOrders.Find(id);
            if (cleaningOrder == null)
            {
                return HttpNotFound();
            }
            return View(cleaningOrder);
        }

        // POST: CleaningOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CleaningOrder cleaningOrder = db.CleaningOrders.Find(id);
            db.CleaningOrders.Remove(cleaningOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteSelected (int id)
        {
            CleaningOrder cleaningOrder = db.CleaningOrders.Find(id);
            db.CleaningOrders.Remove(cleaningOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Paynow()
        {


            return RedirectToAction("Success");
        }
        public ActionResult Success()
        {
            return View();

        }

        #region Fields

        private readonly PayFastSettings payFastSettings;

        #endregion Fields

        #region Constructor


        #endregion Constructor

        #region Methods



        public ActionResult Recurring()
        {
            var recurringRequest = new PayFastRequest(this.payFastSettings.PassPhrase);
            // Merchant Details
            recurringRequest.merchant_id = this.payFastSettings.MerchantId;
            recurringRequest.merchant_key = this.payFastSettings.MerchantKey;
            recurringRequest.return_url = this.payFastSettings.ReturnUrl;
            recurringRequest.cancel_url = this.payFastSettings.CancelUrl;
            recurringRequest.notify_url = this.payFastSettings.NotifyUrl;
            // Buyer Details
            recurringRequest.email_address = "nkosi@finalstride.com";
            // Transaction Details
            recurringRequest.m_payment_id = "8d00bf49-e979-4004-228c-08d452b86380";
            recurringRequest.amount = 20;
            recurringRequest.item_name = "Recurring Option";
            recurringRequest.item_description = "Some details about the recurring option";
            // Transaction Options
            recurringRequest.email_confirmation = true;
            recurringRequest.confirmation_address = "drnendwandwe@gmail.com";
            // Recurring Billing Details
            recurringRequest.subscription_type = SubscriptionType.Subscription;
            recurringRequest.billing_date = DateTime.Now;
            recurringRequest.recurring_amount = 20;

IzintoCleaning/Views/CleaningOrders/Confirmation.cshtml
@model IEnumerable<IzintoCleaning.Models.CleaningOrder>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cleaning.PackageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.CustName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmpmloyeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.area)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.storey)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfService)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.areacost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.floorcost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cleaning.PackageName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.CustName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmpmloyeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.storey)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfService)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.areacost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.floorcost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.address)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Order_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Order_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Order_ID })
        </td>
    </tr>
}

</table>

IzintoCleaning/Views/CleaningOrders/Create.cshtml
@model IzintoCleaning.Models.CleaningOrder

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CleaningOrder</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Package_ID, "Cleaning Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Package_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Package_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustID, "Your Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.area, "House Size(sq meters)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.storey, "Number of floors", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.storey, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.storey, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cost, "Final Cost", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfService, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfService, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfService, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.areacost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.areacost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.areacost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.floorcost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.floorcost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.floorcost, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    <div class="input_field">
        <div class="input-group">


        </div>
        @*<textarea type="text" class="form-control" id="Physical_Address" ng-model="PropertyModel.Physical_Address" required ng-minlength="3" ng-maxlength="255" style="min-height:100px; resize:none" placeholder="Physical Address"></textarea>*@
        <div id="locationField">
            @Html.LabelFor(model => model.address, "Address", htmlAttributes: new { @class = "control-label col-md-2" })
            <input id="address" name="address" placeholder="Enter your address here" required class="form-control" onFocus="geolocate()" @*type="text" style="min-width:360px"*@ />
        </div>
        <br />
    </div>

    <div class="clearfix"></div>

    <script type="text/javascript">
        $(function () {
            $('a[title]').tooltip();
        });
    </script>
    <script>
      // This example displays an address form, using the autocomplete feature
      // of the Google Places API to help users fill in the information.

      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      function initAutocomplete() {
        // Create the autocomplete object, restricting the search to geographical
        // location types.
          address = new google.maps.places.Autocomplete(
            @*/** @type {!HTMLInputElement} */*@(document.getElementById('address')),
            {types: ['geocode']});

        // When the user selects an address from the dropdown, populate the address
        // fields in the form.
          address.addListener('place_changed', fillInAddress);
      }

      function fillInAddress() {
        // Get the place details from the autocomplete object.
          var place = address.getPlace();

        for (var component in componentForm) {
            document.getElementById(component).value = '';
            document.getElementById(component).disabled = false;
        }

        // Get each component of the address from the place details
        // and fill the corresponding field on the form.
        for (var i = 0; i < place.address_components.length; i++) {
          var addressType = place.address_components[i].types[0];
          if (componentForm[addressType]) {
            var val = place.address_components[i][componentForm[addressType]];
            document.getElementById(addressType).value = val;
          }
        }
      }

      // Bias the autocomplete object to the user's geographical location,
      // as supplied by the browser's 'navigator.geolocation' object.
      function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = {
              lat: position.coords.latitude,
              lng: position.coords.longitude
            };
            var circle = new google.maps.Circle({
              center: geolocation,
              radius: position.coords.accuracy
            });
              address.setBounds(circle.getBounds());
          });
        }
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAay3hs9-BpmDIMIcmcA-KDGdqZeOEOoV8&libraries=places&callback=initAutocomplete"
            async defer></script>
    <script>
        $(function () {
            var input = document.getElementById("address");
            var address = new google.maps.places.Autocomplete(input);

            $('#my-modal').modal('show');

        });

    </script>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="View Final Amount" name="btn1" class="btn btn-default" />
            <input type="submit" value="Confirm Order" name="btn1" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Unpaid Requests", "Index")
</div>

<div>
    @Html.ActionLink("Previous Orders", "PrevOrders")
</div>

IzintoCleaning/Views/CleaningOrders/Delete.cshtml
@model IzintoCleaning.Models.CleaningOrder

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CleaningOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cleaning.PackageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cleaning.PackageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CustName)
        </dd>

        <dt>
           Assigned Employee
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpmloyeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.storey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.storey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfService)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfService)
        </dd
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IzintoCleaning/Views/CleaningOrders/Details.cshtml
@model IzintoCleaning.Models.CleaningOrder

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CleaningOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cleaning.PackageName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cleaning.PackageName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customer.CustName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.CustName)
        </dd>

        <dt>
            Assigned Employee
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpmloyeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.storey)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.storey)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfService)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfService)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Order_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IzintoCleaning/Views/CleaningOrders/Index.cshtml
@model IEnumerable<IzintoCleaning.Models.CleaningOrder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Unpaid Requests</h2>

<p>
    @Html.ActionLink("Request A Service", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Description
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.CustName)
        </th>
        <th>
            Employee
        </th>
        <th>
            House Size
        </th>
        <th>
            Floors
        </th>
        <th>
            Final
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfService)
        </th>
        <th>
           Address
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cleaning.PackageName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.CustName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmpmloyeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.area) sq meter
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.storey)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfService)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.address)
        </td>
        @if (User.IsInRole("Admin"))
        {
            <td>
                @Html.ActionLink("Assign Employee", "Create", "EmployeeOrders")
            </td>
        }
        else
        {
            <td>
                <div class="btn">
                    <div>
                        <a href="@Url.Action("Edit", "CleaningOrders", new { id=item.Order_ID})">
                            <input type="submit" value="Edit Order" class="btn  pull-right btn-success" />
                        </a>
                    </div>
                </div>
            </td>
            <td>
                  <div class="btn">
                        <div>
                            <a href="@Url.Action("OnceOff", "CleaningOrders", new { id=item.Order_ID})">
                                <input type="submit" value="Pay" class="btn  pull-right btn-success" />
                            </a>
                        </div>
                    </div>
                

            </td>
            <td>



                <div class="btn">
                    <div>
                        <a href="@Url.Action("DeleteSelected", "CleaningOrders", new { id=item.Order_ID})">
                            <input type="submit" value="Cancel" class="btn  pull-right btn-danger" data-toggle="modal" data-target="#exampleModal" />

                    </div>
                </div>

                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Cleaning Order</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <h3>Are you sure you want to cancel your Cleaning Order?</h3>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>

                                <button type="button" class="btn btn-primary" href="@Url.Action("DeleteSelected", "CleaningOrders", new { id=item.Order_ID})">Yes</button>
                            </div>
                        </div>
                    </div>
                </div>


            </td>
        }
    </tr>
}

</table>