IzintoCleaning/Models/Cleaning.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations.Schema;

namespace IzintoCleaning.Models
{
    public class Cleaning
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Package_ID { get; set; }

        public int SerCode { get; set; }
        [ForeignKey("SerCode")]
        public virtual Service service { get; set; }

        [Required]
        [MinLength(5)]
       public string PackageName { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        public decimal CostArea { get; set; }

        [DataType(DataType.Currency)]
        [Required]
        public decimal CostStorey { get; set; }
    }
}

IzintoCleaning/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations.Schema;


namespace IzintoCleaning.Models
{
    public class Employee
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EmpID { get; set; }

        [DisplayName("Employee Name")]
        [Required(ErrorMessage = "Name is required")]
        public string EmpName { get; set; }

        [DisplayName("Employee Surname")]
        [Required(ErrorMessage = "Surname is required")]
        public string EmpSurame { get; set; }

        [DisplayName("Employee Email")]
        [Required(ErrorMessage = "Email is required")]
        public string EmpEmail { get; set; }

        [DisplayName("Employee Phone")]
        [MaxLength(10, ErrorMessage = "Phone number must only be 10 digits long"), MinLength(10, ErrorMessage = "Phone number must be 10 digits long")]
        [Required(ErrorMessage = "Phone is required")]
        public string EmpPhone { get; set; }

        [DisplayName("Employee Address")]
        [Required(ErrorMessage = "Address is required")]
        public string EmpAddress { get; set; }

        [DataType(DataType.Currency)]
        [DisplayName("Expected Pay")]
        [Required(ErrorMessage = "Address is required")]
        public decimal Wage { get; set; }

        [Required(ErrorMessage = "Employee status is required")]
        [DisplayName("Employee Status")]
        public Availabity EmployeeStatus { get; set; }

        public string Status { get; set; }

        public IEnumerable<SelectListItem> Statuses { set; get; }

        public string AdminID { get; set; }
        [ForeignKey("AdminID")]
        public virtual Admin admin { get; set; }

        public int SerCode { get; set; }
        [ForeignKey("SerCode")]
        public virtual Service service { get; set; }
        public DateTime? Today { get; set; }

        ApplicationDbContext db = new ApplicationDbContext();
        public decimal getWage()
        {
            var wage = (from i in db.Service where SerCode == i.SerCode select i.SerWage).SingleOrDefault();
            return wage;
        }

        public string Availabilty()
        {
            
            if (EmployeeStatus == Availabity.N)
            {
                Status = "Busy";

            }
            else if (EmployeeStatus == Availabity.Y)
            {
                Status = "Available";
            }

            return Status;
        }
    }

    public enum Availabity
        {
            Y,
            N
            
        }
    
}

IzintoCleaning/Controllers/CleaningsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IzintoCleaning.Models;

namespace IzintoCleaning.Controllers
{
    public class CleaningsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cleanings
        public ActionResult Index()
        {
            var cleanings = db.Cleanings.Include(c => c.service);
            return View(cleanings.ToList());
        }

        // GET: Cleanings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cleaning cleaning = db.Cleanings.Find(id);
            if (cleaning == null)
            {
                return HttpNotFound();
            }
            return View(cleaning);
        }

        // GET: Cleanings/Create
        public ActionResult Create()
        {
            ViewBag.SerCode = new SelectList(db.Service.Where(s => s.SerName == "Cleaning"), "SerCode", "SerName");
            return View();
        }

        // POST: Cleanings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Package_ID,SerCode,PackageName,CostArea,CostStorey")] Cleaning cleaning)
        {
            if (ModelState.IsValid)
            {
                db.Cleanings.Add(cleaning);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SerCode = new SelectList(db.Service, "SerCode", "SerName", cleaning.SerCode);
            return View(cleaning);
        }

        // GET: Cleanings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cleaning cleaning = db.Cleanings.Find(id);
            if (cleaning == null)
            {
                return HttpNotFound();
            }
            ViewBag.SerCode = new SelectList(db.Service.Where(s => s.SerName == "Cleaning"), "SerCode", "SerName", cleaning.SerCode);
            return View(cleaning);
        }

        // POST: Cleanings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Package_ID,SerCode,PackageName,CostArea,CostStorey")] Cleaning cleaning)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cleaning).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SerCode = new SelectList(db.Service, "SerCode", "SerName", cleaning.SerCode);
            return View(cleaning);
        }

        // GET: Cleanings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cleaning cleaning = db.Cleanings.Find(id);
            if (cleaning == null)
            {
                return HttpNotFound();
            }
            return View(cleaning);
        }

        // POST: Cleanings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cleaning cleaning = db.Cleanings.Find(id);
            db.Cleanings.Remove(cleaning);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IzintoCleaning/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IzintoCleaning.Models;

namespace IzintoCleaning.Controllers
{
    public class EmployeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Employees
        /* public ActionResult Index(/*string selectStatus)
         {
            var vm = new ListAndSearchVM();

             vm.Statuses = new List<SelectListItem> {
                 new SelectListItem { Value = "Available", Text = "Available" },
                 new SelectListItem {Value = "Not Available", Text= "Not Available"}
             };

             var data = db.Employees;
             if(!String.IsNullOrEmpty(selectStatus))
             {
               //  data = data.Where(f => f.Status == selectStatus);
             }
             vm.Employees = data.ToList();

             var employees = db.Employees.Include(e => e.admin).Include(e => e.service);
             return View(employees.ToList());
         }*/

        public ActionResult Index(string searchString, string sortOrder)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "avalaibity" : "";
            //ViewBag.AvailabilitySortParm = sortOrder == "Avalaible" ? "Not Available" : "";
            var employee = from s in db.Employees
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                employee = employee.Where(s => s.EmpSurame.Contains(searchString)
                                       || s.EmpName.Contains(searchString)
                                       || s.Status.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    employee = employee.OrderByDescending(s => s.EmpSurame);
                    break;
                /*case "avalaibity":
                    employee = employee.OrderByDescending(s => s.Status);
                    break;
                /*case "date_desc":
                    employee = employee.OrderByDescending(s => s.EmployeeStatus);
                    break;*/
                default:
                    employee = employee.OrderBy(s => s.EmpSurame);
                    break;
            }

            return View(employee.ToList());


        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.AdminID = new SelectList(db.admin, "AdminID", "AdminName");
            ViewBag.SerCode = new SelectList(db.Service, "SerCode", "SerName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmpID,EmpName,EmpSurame,EmpEmail,EmpPhone,EmpAddress,Wage,AdminID,SerCode,,Status,EmployeeStatus")] Employee employee)
        {
            employee.Wage = employee.getWage();
            if (ModelState.IsValid)
            {
                string str = Request.Params["btn1"];
                if (str == "Examine")
                {
                    employee.Wage = employee.getWage();

                }
                else if (str == "Confirm")
                {
                    employee.Status = employee.Availabilty();
                    employee.Wage = employee.getWage();

                    db.Employees.Add(employee);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.AdminID = new SelectList(db.admin, "AdminID", "AdminName", employee.AdminID);
            ViewBag.SerCode = new SelectList(db.Service, "SerCode", "SerName", employee.SerCode);
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.AdminID = new SelectList(db.admin, "AdminID", "AdminName", employee.AdminID);
            ViewBag.SerCode = new SelectList(db.Service, "SerCode", "SerName", employee.SerCode);
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmpID,EmpName,EmpSurame,EmpEmail,EmpPhone,EmpAddress,Wage,AdminID,SerCode,Status,EmployeeStatus")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                string str = Request.Params["btn1"];
                if (str == "Examine")
                {
                    employee.Wage = employee.getWage();

                }
                else if (str == "Confirm")
                {
                    employee.Wage = employee.getWage();
                    employee.Status = employee.Availabilty();
                    
                    db.Entry(employee).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.AdminID = new SelectList(db.admin, "AdminID", "AdminName", employee.AdminID);
            ViewBag.SerCode = new SelectList(db.Service, "SerCode", "SerName", employee.SerCode);
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IzintoCleaning/Views/Shared/EquipmentInfo.cshtml
@model IzintoCleaning.Models.CustomerEquipment

<table>
    <tr>
        <td>
            <strong>@Html.Label("Equipment Name : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.EquipType, new { htmlAttributes = new { @class = "form-control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Equipment type : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.EquipType, new { htmlAttributes = new { @class = "form-control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Equipment cost : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.EquipCost, new { htmlAttributes = new { @class = "form - control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Amount to pay : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.FinalCost, new { htmlAttributes = new { @class = "form - control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Supplied By : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.suppName, new { htmlAttributes = new { @class = "form - control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Supplier Email : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.suppEmail, new { htmlAttributes = new { @class = "form - control" } }) </td>
    </tr>
</table>

IzintoCleaning/Views/Shared/ErrorCost.cshtml
@{
    ViewBag.Title = "Error";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">Please</h2>

IzintoCleaning/Views/Shared/_ApplicantList.cshtml
@model IEnumerable<IzintoCleaning.Models.Applicant>

IzintoCleaning/Views/Shared/_ApplicationInfo.cshtml
@model IzintoCleaning.Models.PostApplication

<table>

   @* <tr>
        <td>
            <strong>@Html.Label("Service Name : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.SerCode, new { htmlAttributes = new { @class = "form-control" } }) </td>
    </tr>*@
    <tr>
        <td>
            <strong>@Html.Label("Expected Wage : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.wage, new { htmlAttributes = new { @class = "form-control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Post Description : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.postDescription, new { htmlAttributes = new { @class = "form-control" } }) </td>
    </tr>
    <tr>
        <td>
            <strong>@Html.Label("Closing Date : ")</strong>
        </td>
        <td> @Html.DisplayFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form - control" } }) </td>
    </tr>

</table>

IzintoCleaning/Views/Shared/_Cleaning.cshtml
@model IzintoCleaning.Models.CustomerService

@{
    ViewBag.Title = "Request A Service";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Fill In All Fields</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustID, "Your Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescID, "Service Package", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DescID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DescID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.SerCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerCodeCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.SerCodeCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerCodeCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinalCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FinalCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinalCost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfService, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfService, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfService, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="View Final Amount" name="btn1" class="btn btn-default" />
                <input type="submit" value="Confirm Order" name="btn1" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IzintoCleaning/Views/Shared/_Employees.cshtml
@model IEnumerable<IzintoCleaning.Models.Employee>

   

IzintoCleaning/Views/Shared/_EquipmentList.cshtml
@model IEnumerable<IzintoCleaning.Models.Equipment>

IzintoCleaning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/MyMainLayOut.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">

        <div class="row">
            <div class="col-lg-6">
                <div class="logo">
                    <h1><a @Html.ActionLink("Izinto Cleaning", "Index", "Home")</a></h1>
                    <p>Services You Can Trust</p>
                </div>
            </div>
            @*@{

                var cart_Service = new IzintoCleaning.Models.Cart_Service();
                decimal total = 0;
            }*@
            <div class="col-lg-6">
                <div class="account">
                    <ul>
                        <li>
                            <div class="hidden-xs">
                                @Html.Partial("_LoginPartial")

                            </div>

                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-lg-12">
                <div class="nav-menus">


                    @if (User.IsInRole("Admin"))
                    {
                    <ul class="nav nav-pills">
                        <li class="active" style="border-radius:initial;"> @Html.ActionLink("Home", "Index", "Home")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Suppliers", "Index", "Suppliers")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Services", "Index", "Services")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Employee", "Index", "Employees")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Equipment", "Index", "Equipments")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Assign Role", "AddRole", "Roles")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Cleaning Requests", "Index", "CleaningOrders")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Gardening Requests", "Index", "GardeningOrders")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Fumigate Requests", "Index", "FumigationOrders")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Register Admin", "AdminReg", "Account")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Fumigation", "Create", "Fumigations")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Cleaning", "Create", "Cleanings")</li>
                        <li style="border-radius:initial;"> @Html.ActionLink("Gardening", "Create", "Gardenings")</li>
                    </ul>
                    }
                    else
                    {
                        <ul class="nav nav-pills">
                            <li class="active" style="border-radius:initial;"> @Html.ActionLink("Home", "Index", "Home")</li>
                            <li style="border-radius:initial;"> @Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li style="border-radius:initial;"> @Html.ActionLink("Browse Equipment", "Index", "Shopping")</li>
                            <li style="border-radius:initial;"> @Html.ActionLink("Garden", "Create", "GardeningOrders")</li>
                            <li style="border-radius:initial;"> @Html.ActionLink("Clean", "Create", "CleaningOrders")</li>
                            <li style="border-radius:initial;"> @Html.ActionLink("Fumigate", "Create", "FumigationOrders")</li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-list"></span>Shop <span class="caret"></span></a>
                                <ul class="dropdown-menu mega scrollable-menu">


                                    <li>
                                        <a href="#">
                                            <i class="fa fa-shopping-cart"></i> <span> Cart</span>
                                            (@Html.Action(actionName: "countCartItems", controllerName: "Shopping"))<span class="caret"></span>

                                            <i class="fa fa-angle-left pull-right"></i>
                                        </a>
                                    </li>

                                    <li><a href="~/Shopping/Index"><i class="fa fa-circle-o"></i>  Shop More</a></li>

                                    <li><a href="~/Shopping/ShoppingCart"><i class="fa fa-circle-o"></i>View Cart </a></li>



                                </ul>
                            </li>

                        </ul>
                    }

                </div>
            </div>

        </div>
        <hr/>

        @RenderBody()

        <hr />
        <footer>
            <div class="row">
                <div class="col-lg-12 copyright">

                    <div class="col-lg-6 col-sm-6 copyright-left">
                        <p>&copy; @DateTime.Now.Year - Izinto Cleaning. All right reserved.</p>
                    </div>

                    <div class="col-lg-6 col-sm-6 copyright-right">

                    </div>
                </div>
            </div>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>